name: run-tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"
          architecture: x64
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew test
